### ISSUE TITLE
ask for ansible-operator for UBI9 , so far still only see UBI8, need operator based on UBI9/RHEL9 

### ISSUE THREAD

**Issue by wying3** [operator-framework/ansible-operator-plugins#29]
#### Describe the problem you need a feature to resolve.

we are running on OpenShift Platform 4.13 which is based on UBI9, but the current latest version available is still based on UBI8
https://quay.io/repository/operator-framework/ansible-operator?tag=latest&tab=tags 

can you let me know when can expect to have new image available based on UBI9/RHEL9?

#### Describe the solution you'd like.

wait for new version of operator available based on UBI9/RHEL9

ansible-operator

**Comment by prashant20verma** [comment]
When can we expect ansible-operator image based on UBI9 be available ?

**Comment by YanFenGuo** [comment]
Requesting the same, when can have ubi 9 based ansible-operator image?

**Comment by darrentma** [comment]
I noticed that the "main" branch was bumped to UBI 9 on Oct 10, 2024.  
https://github.com/operator-framework/ansible-operator-plugins/commit/0818d9aba49373b9007851aeca666708494c1464

What is the expected ETA for the next release of "ansible-image" to be tagged that will include this change to UBI 9?  It has been 3 months since "v1.35" was tagged. 

Thanks!
