### ISSUE TITLE
[Kiali] stop the reconciliation to other namespaces

### ISSUE THREAD

**Issue by NelsonLomboPaez** [operator-framework/ansible-operator-plugins#68]
#### Describe the problem you need a feature to resolve.

On multitenant clusters that have a lot of Kiali deployed, every time a namespace is created or modified, all of those Kiali instances are going to be reconciled which will create some consumption spikes and some performance degradation on the cluster

#### Describe the solution you'd like.

It would be great to have the option to stop the synchronization from a Kiali instance to other namespaces that are not managed by that instance.

Maybe something like this could help --> https://github.com/operator-framework/ansible-operator-plugins/pull/45

**Comment by jmazzitelli** [comment]
I suspect this issue is not needed and should be closed. It is more related to an issue with the kiali operator. I did , however, ask for a feature request to the ansible operator SDK to help solve that issue with the kiali operator (see https://github.com/operator-framework/ansible-operator-plugins/issues/20) but it went stale and likely will not get done. So I have a solution I'm trying out that can be done within the kiali operator itself. See the [issue](https://github.com/operator-framework/ansible-operator-plugins/issues/20) and [PR](https://github.com/kiali/kiali-operator/pull/762) for those interested.
